[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=86400"
[[plugins]]
package = "netlify-plugin-contextual-env"
  [plugins.inputs]
  mode = 'prefix'
